enable: true
server: "ldap.caiwu.corp"
port: 389
useSSL: false
bindUser: "paas_ldap"
bindPassword: "!%!!))#6203qqq"
bindDN: "OU=宜信公司,OU=HABROOT,DC=creditease,DC=corp"
attributes:
  - "userPrincipalName"
  - "sAMAccountName"
  - "displayName"
  - "mail"
  - "telephoneNumber"
  - "name"
userFilter: "(mail=%s)"