supportUsers:
  - userID: "6612463495"
    nickname: "信贷资产"
  - userID: "5236095813" 
    nickname: "RMB类投前-股权/资本市场"
  - userID: "5504935740"
    nickname: "RMB类投后-股权/资本市场"
  - userID: "1184869903"
    nickname: "USD类-股权/资本市场"
  - userID: "1392757745"
    nickname: "瑞承国际"
  - userID: "6658180562"
    nickname: "客户关系"
  - userID: "4511414733"
    nickname: "数据报表提供"
  - userID: "2487422663"
    nickname: "税小盈"
  - userID: "4981778861"
    nickname: "瑞承系统（技术）问题"